# frozen_string_literal: true

# Default ApplicationHelper class generated by Rails when creating a new project
module ApplicationHelper
  def value_as_money(value)
    number_to_currency(value, unit: 'R$ ', separator: ',', delimiter: '.')
  end

  def date_br(date)
    date.in_time_zone('Brasilia').strftime('%d/%m/%Y %H:%M')
  end
end
