openapi: 3.0.1
info:
  title: CNAB Manager API
  description: This is the documentation for the CNAB Manager API. This API is very simple and is only intended to demonstrate how it would be documented if it was
    a bigger project with a complex API.
  contact:
    email: juscezari@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:3000/api/v1
tags:
- name: CNAB
  description: Endpoints for transactions
paths:
  /transactions:
    get:
      tags:
      - CNAB
      summary: Return all transactions in the system
      description: This endpoint will return all transactions saved in the system
        or all transactions filtered by store name or transaction type.
      parameters:
      - name: store_name
        in: query
        description: Store name that need to be considered for filter
        schema:
          type: string
      - name: transaction_type
        in: query
        description: Transaction type that need to be considered for filter
        schema:
          type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
  /transactions/{id}:
    get:
      tags:
      - CNAB
      summary: Find transaction by ID
      description: Returns a single transaction
      parameters:
      - name: id
        in: path
        description: ID of transaction to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
          description: Transaction ID
          format: int64
          example: 1
        transaction_type:
          type: integer
          description: Transaction type
          format: int64
          example: 3
        date:
          type: string
          description: Date that the transaction occurred
          format: date-time
        value:
          type: number
          description: Transaction value
          format: float
          example: 234.11
        cpf:
          type: string
          description: CPF vinculated to the transaction
          example: "12345678910"
        card_number:
          type: string
          description: Card number in the transaction
          example: 1234****5678
        owner_name:
          type: string
          description: Owner of the store where the transaction occurred
          example: Julio de Lara
        store_number:
          type: string
          description: Store name where the transaction occurred
          example: Awesome Shop
        created_at:
          type: string
          description: Date that the transaction was saved in the system
          format: date-time
        updated_at:
          type: string
          description: Date of the last update of the transaction in the system
          format: date-time
