# frozen_string_literal: true

# Default ApplicationMailer class generated by Rails when creating a new project
class ApplicationMailer < ActionMailer::Base
  default from: 'from@example.com'
  layout 'mailer'
end
